### ISSUE TITLE
fusion_rules not match 

### ISSUE THREAD

**Issue by XYAskWhy** [microsoft/nn-Meter#65]
In your open-sourced cortexA76cpu_tflite21 predictor fusion_rules.json file, I found:
> "RBC": {
   "latency": {},
   "obey": null
  },
  "CBC": {
   "latency": {},
   "obey": null
  },
  "BF_bn_relu": {
    "obey": true
  },
  "BF_conv_bn": {
    "obey": true
  },
  "BF_dwconv_bn": {
    "obey": true
  },
  "BF_conv_bn_relu": {
    "obey": true
  },
  "BF_dwconv_bn_relu": {
   "obey": true
  }

do you mean these kernels are naturally fused and hence doesn't need to detect? Why it that? Do I need to add all those to my own detected_fusion_rule.json?

What's more, in the fusion_rules.json, the fusion rules you seem to have detected are: 

> se_relu, pooling_reshape, dense_concat, dense_add, dense_relu, concat_dense, conv_pooling, conv_relu, add_relu, relu_dense, relu_relu, dwconv_relu, reshape_convtrans, reshape_conv, reshape_relu, reshape_reshape. 

But in this [page](https://github.com/microsoft/nn-Meter/blob/main/docs/kernel.md), you claim that the CPU kernel are: 

>  conv-relu,fc,maxpool,global-avgpool,fc-relu,concat,avgpool,conv-bn-relu,bn-relu,conv,SE-relu,conv-bn,dwconv-bn,dwconv-bn-relu,add,hswish,SE,conv-bn-bn-relu,relu,add-relu,channelshuffle,split.

Those two are very different, why?
What confuses me even more is, in the default predictorbuild_config.yaml, the kernels are: 

> conv-bn-relu, dwconv-bn-relu, maxpool, avgpool, fc, concat, split, channelshuffle, se, global-avgpool, bnrelu, bn, hswish, relu, addrelu, add.

Although you mentioned, in the same [page](https://github.com/microsoft/nn-Meter/blob/main/docs/kernel.md),  that we can use one conv-bn-relu kernel to represent all conv-related kernels, the rest are still a bit different with your claimed cpu kernels. Does this mean we can merge other kernels to a general kernel as well? And what's the rule for that? 

I have this issue, because I want to reproduce your results on a a78 cpu, but I get a very different fusion_rules results with yours,  and I don't know what to do with it. Should I implement all the new kernels, or should I merge some of these kernels? My results of detected_fusion_rule.json on a78 cpu are:

> add_avgpool, add_concat, add_conv, add_relu, avgpool_add, avgpool_concat, avgpool_relu, avgpool_reshape, concat_convtrans, concat_fc, conv_relu, convtrans_relu, fc_relu, dwconv_add,
dwconv_relu, relu_avgpool,relu_concat,relu_conv,relu_convtrans,relu_relu,reshape_concat,reshape_conv,
reshape_convtrans,reshape_dwconv,reshape_reshape

**Comment by JiahangXu** [comment]
Hi, thanks for raising the issue. 

First of all, the fusion rules in `fusion_rules.json` indicates whether two ops will be fused in the corresponding device. When there comes a network for latency prediction, nn-meter will do: 1. parse the network to get the network structure, and convert the network architecture to nn-meter ir graph; 2. detect all kernels based on `fusion_rules.json` of the predictor, for example, if "bn_relu" and "conv_bn" both obey the fusion ("BF_bn_relu": {"obey": true}, "BF_conv_bn": {"obey": true}), then all "conv + bn + relu" in the network will be fused to a kernel "conv-bn-relu"; 3. go through the network after kernel detection, and predict kernel-wise latency based on the kernel configs.

In your mentioned fusion rules, "CBC" and "RBC" are legacy test cases, so that there is no need to test these two cases when building your own predictor. Furthermore, nn-Meter building tools also removed test cases of fusing three ops such as "conv_bn_relu" and "dwconv_bn_relu", since the kernel "conv_bn_relu" will be detected by "conv_bn" and "bn_relu".

As for your second question, the detected kernel is based on fusion rules but not equal to fusion rules. As I mentioned before, a detected kernel of "conv_bn_relu" should based on two fusion rules, "conv_bn" and "bn_relu". In the released CPU predictor "cortexA76cpu_tflite21", we have tested all fusion rules and summarized all detected kernels in [this page](https://github.com/microsoft/nn-Meter/blob/main/docs/kernel.md).

The third question is about the default `predictorbuild_config.yaml`. Here we only listed some common kernel for prediction. However, the kernel relies on both the inference framework and the hardware, as both of them impact the fusion rules. We suggest detect fusion rules for your own backend, and then determine all kernels by fusion rule detection results.

The last question about whether to merge some kernels into one predictor, my suggestion is to take a look at the profiling latency. According to our experience, the latency of concat/reshape/add/relu are relatively small when compared with conv/dwconv/fc op (which we call it a dominant op). If you found two kernels with the same dominant op has similar latency results, you could consider to merge the two kernels in one predictor.
